import { test, expect } from "@playwright/test";

const password = "Browser test passphrase!";

test("desktop member registration, profile, reservation, password and logout", async ({ page }) => {
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.goto("/en/register");
  await page.getByLabel("Full name", { exact: true }).fill("Browser Member");
  await page.getByLabel("Email address", { exact: true }).fill("browser@example.com");
  await page.getByLabel("Phone number", { exact: true }).fill("0812345678");
  await page.getByLabel("Password", { exact: true }).fill(password);
  await page.getByLabel("Confirm password", { exact: true }).fill(password);
  await page.getByRole("button", { name: "Create account", exact: true }).click();
  await expect(page).toHaveURL(/\/en\/account$/);
  await expect(page.getByRole("heading", { level: 1 })).toHaveText("Browser Member");
  await page.getByLabel("Full name", { exact: true }).fill("Updated Browser Member");
  await page.getByRole("button", { name: "Save changes", exact: true }).click();
  await expect(page.getByRole("status")).toHaveText("Your details have been saved.");
  await expect(page.getByRole("heading", { level: 1 })).toHaveText("Updated Browser Member");
  await page.goto("/en/reservations?date=2099-10-10&time=19%3A00&guests=2");
  await page.getByRole("button", { name: "Continue", exact: true }).click();
  await page.getByRole("button", { name: "Continue", exact: true }).click();
  await expect(page.locator("#first-name")).toHaveValue("Updated");
  await expect(page.locator("#last-name")).toHaveValue("Browser Member");
  await expect(page.locator("#email")).toHaveValue("browser@example.com");
  await expect(page.locator("#phone")).toHaveValue("0812345678");
  await page.getByRole("button", { name: "Continue", exact: true }).click();
  const savedBooking = page.waitForResponse((response) => response.url().endsWith("/api/reservations") && response.request().method() === "POST");
  await page.getByRole("button", { name: "Confirm Reservation", exact: true }).click();
  const created = await savedBooking;
  expect(created.status()).toBe(201);
  const booking = (await created.json()).data;
  await expect(page).toHaveURL(new RegExp(`/en/reservations/confirmation\\?ref=${booking.reservationCode}`));
  await page.goto(`/en/reservations/confirmation?ref=${booking.reservationCode}&date=2020-01-01`);
  await expect(page.locator(".confirmation-details")).toContainText(booking.reservationCode);
  await expect(page.locator(".confirmation-details")).toContainText("2099");
  await page.goto("/en/account/reservations");
  await expect(page.locator(".reservation-list")).toContainText(booking.reservationCode);
  await page.goto("/en/admin");
  await expect(page).toHaveURL(/\/en\/account$/);
  const forbidden = await page.request.get("/api/customers");
  expect(forbidden.status()).toBe(403);
  await page.getByLabel("Current password", { exact: true }).fill(password);
  await page.getByLabel("New password", { exact: true }).fill("Changed browser passphrase!");
  await page.getByLabel("Confirm password", { exact: true }).fill("Changed browser passphrase!");
  await page.getByRole("button", { name: "Update password", exact: true }).click();
  await expect(page.getByRole("status")).toHaveText("Password updated. Your other sessions have been signed out.");
  await page.getByRole("button", { name: "Sign out", exact: true }).click();
  await expect(page).toHaveURL(/\/en\/login$/);
  await page.getByLabel("Email address", { exact: true }).fill("browser@example.com");
  await page.getByLabel("Password", { exact: true }).fill(password);
  await page.getByRole("button", { name: "Sign in", exact: true }).click();
  await expect(page.locator(".form-feedback-error")).toContainText("email or password is incorrect");
  await page.getByLabel("Password", { exact: true }).fill("Changed browser passphrase!");
  await page.getByRole("button", { name: "Sign in", exact: true }).click();
  await expect(page).toHaveURL(/\/en\/account$/);
  await page.screenshot({ path: "test-results/account-desktop.png", fullPage: true });
  expect(errors).toEqual([]);
});

test("Thai mobile forms, validation and return to booking after login", async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto("/th/reservations?date=2099-10-11&time=19%3A00&guests=3");
  await expect(page).toHaveURL(/\/th\/login\?next=/);
  await page.getByRole("link", { name: "สมัครสมาชิก", exact: true }).click();
  await page.getByRole("button", { name: "สมัครสมาชิก", exact: true }).click();
  await expect(page.locator(".form-feedback-error")).toBeFocused();
  await expect(page.locator(".form-feedback-error")).toContainText("กรอกอีเมลให้ถูกต้อง");
  await page.getByLabel("ชื่อ–นามสกุล", { exact: true }).fill("สมาชิกทดสอบ");
  await page.getByLabel("อีเมล", { exact: true }).fill("mobile@example.com");
  await page.getByLabel("เบอร์โทรศัพท์", { exact: true }).fill("0899999999");
  await page.getByLabel("รหัสผ่าน", { exact: true }).fill(password);
  await page.getByLabel("ยืนยันรหัสผ่าน", { exact: true }).fill(password);
  await page.getByRole("button", { name: "สมัครสมาชิก", exact: true }).click();
  await expect(page).toHaveURL(/\/th\/reservations\?date=2099-10-11/);
  await page.goto("/th/account");
  await expect(page.getByRole("heading", { level: 1 })).toHaveText("สมาชิกทดสอบ");
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: "test-results/account-mobile.png", fullPage: true });
  await page.getByRole("button", { name: "เปิดเมนูนำทาง" }).click();
  await expect(page.locator("#mobile-navigation").getByRole("link", { name: "บัญชีของฉัน", exact: true })).toBeVisible();
  await page.locator("#mobile-navigation").getByRole("link", { name: "บัญชีของฉัน", exact: true }).click();
  await expect(page.locator("#mobile-navigation")).toHaveCount(0);
});

test("seeded admin signs in, uses dashboard and changes their own profile", async ({ page }) => {
  await page.goto("/en/admin/login");
  await page.getByLabel("Email address", { exact: true }).fill("staff@example.com");
  await page.getByLabel("Password", { exact: true }).fill("Staff test passphrase!");
  await page.getByRole("button", { name: "Sign in", exact: true }).click();
  await expect(page).toHaveURL(/\/en\/admin$/);
  await expect(page.getByRole("heading", { name: "Today's Overview" })).toBeVisible();
  expect((await page.request.get("/api/customers")).status()).toBe(200);
  await page.goto("/en/account");
  await expect(page.locator(".account-tabs").getByRole("link", { name: "Staff dashboard" })).toBeVisible();
  await page.getByLabel("Full name", { exact: true }).fill("Updated Staff");
  await page.getByRole("button", { name: "Save changes", exact: true }).click();
  await expect(page.getByRole("heading", { level: 1 })).toHaveText("Updated Staff");
  await page.getByRole("button", { name: "Sign out", exact: true }).click();
  await expect(page).toHaveURL(/\/en\/login$/);
  await page.goto("/en/admin");
  await expect(page).toHaveURL(/\/en\/admin\/login$/);
});
